// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataFormat int32

const (
	DataFormat_TEXT    DataFormat = 0
	DataFormat_PARQUET DataFormat = 1
	DataFormat_JSON    DataFormat = 2
)

// Enum value maps for DataFormat.
var (
	DataFormat_name = map[int32]string{
		0: "TEXT",
		1: "PARQUET",
		2: "JSON",
	}
	DataFormat_value = map[string]int32{
		"TEXT":    0,
		"PARQUET": 1,
		"JSON":    2,
	}
)

func (x DataFormat) Enum() *DataFormat {
	p := new(DataFormat)
	*p = x
	return p
}

func (x DataFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_client_proto_enumTypes[0].Descriptor()
}

func (DataFormat) Type() protoreflect.EnumType {
	return &file_proto_client_proto_enumTypes[0]
}

func (x DataFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataFormat.Descriptor instead.
func (DataFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{0}
}

// Messages from client to boss
type ClientToBoss struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientToBoss_Hello
	//	*ClientToBoss_SubmitJob
	Msg           isClientToBoss_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToBoss) Reset() {
	*x = ClientToBoss{}
	mi := &file_proto_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToBoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToBoss) ProtoMessage() {}

func (x *ClientToBoss) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToBoss.ProtoReflect.Descriptor instead.
func (*ClientToBoss) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientToBoss) GetMsg() isClientToBoss_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientToBoss) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Msg.(*ClientToBoss_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientToBoss) GetSubmitJob() *SubmitJobRequest {
	if x != nil {
		if x, ok := x.Msg.(*ClientToBoss_SubmitJob); ok {
			return x.SubmitJob
		}
	}
	return nil
}

type isClientToBoss_Msg interface {
	isClientToBoss_Msg()
}

type ClientToBoss_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientToBoss_SubmitJob struct {
	SubmitJob *SubmitJobRequest `protobuf:"bytes,2,opt,name=submit_job,json=submitJob,proto3,oneof"`
}

func (*ClientToBoss_Hello) isClientToBoss_Msg() {}

func (*ClientToBoss_SubmitJob) isClientToBoss_Msg() {}

// Messages from boss to client
type BossToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*BossToClient_StatusDump
	Msg           isBossToClient_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossToClient) Reset() {
	*x = BossToClient{}
	mi := &file_proto_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossToClient) ProtoMessage() {}

func (x *BossToClient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossToClient.ProtoReflect.Descriptor instead.
func (*BossToClient) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *BossToClient) GetMsg() isBossToClient_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *BossToClient) GetStatusDump() string {
	if x != nil {
		if x, ok := x.Msg.(*BossToClient_StatusDump); ok {
			return x.StatusDump
		}
	}
	return ""
}

type isBossToClient_Msg interface {
	isBossToClient_Msg()
}

type BossToClient_StatusDump struct {
	StatusDump string `protobuf:"bytes,1,opt,name=status_dump,json=statusDump,proto3,oneof"` // Simple string dump of system state
}

func (*BossToClient_StatusDump) isBossToClient_Msg() {}

// Client introduces itself when connecting
type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` // Optional user identification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHello) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// Job submission
type SubmitJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeUri        string                 `protobuf:"bytes,1,opt,name=code_uri,json=codeUri,proto3" json:"code_uri,omitempty"`                                     // Path to user's MapReduce code
	InputFiles     []string               `protobuf:"bytes,2,rep,name=input_files,json=inputFiles,proto3" json:"input_files,omitempty"`                            // Input file paths
	ReducerCount   int32                  `protobuf:"varint,3,opt,name=reducer_count,json=reducerCount,proto3" json:"reducer_count,omitempty"`                     // Number of reduce tasks
	EnableCombiner bool                   `protobuf:"varint,4,opt,name=enable_combiner,json=enableCombiner,proto3" json:"enable_combiner,omitempty"`               // Use combiner optimization
	InputType      DataFormat             `protobuf:"varint,5,opt,name=input_type,json=inputType,proto3,enum=mapreduce.DataFormat" json:"input_type,omitempty"`    // TEXT, PARQUET, JSON
	OutputType     DataFormat             `protobuf:"varint,6,opt,name=output_type,json=outputType,proto3,enum=mapreduce.DataFormat" json:"output_type,omitempty"` // Output format
	OutputDir      string                 `protobuf:"bytes,7,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`                               // Where to store results
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitJobRequest) GetCodeUri() string {
	if x != nil {
		return x.CodeUri
	}
	return ""
}

func (x *SubmitJobRequest) GetInputFiles() []string {
	if x != nil {
		return x.InputFiles
	}
	return nil
}

func (x *SubmitJobRequest) GetReducerCount() int32 {
	if x != nil {
		return x.ReducerCount
	}
	return 0
}

func (x *SubmitJobRequest) GetEnableCombiner() bool {
	if x != nil {
		return x.EnableCombiner
	}
	return false
}

func (x *SubmitJobRequest) GetInputType() DataFormat {
	if x != nil {
		return x.InputType
	}
	return DataFormat_TEXT
}

func (x *SubmitJobRequest) GetOutputType() DataFormat {
	if x != nil {
		return x.OutputType
	}
	return DataFormat_TEXT
}

func (x *SubmitJobRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

var File_proto_client_proto protoreflect.FileDescriptor

const file_proto_client_proto_rawDesc = "" +
	"\n" +
	"\x12proto/client.proto\x12\tmapreduce\"\x83\x01\n" +
	"\fClientToBoss\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.mapreduce.ClientHelloH\x00R\x05hello\x12<\n" +
	"\n" +
	"submit_job\x18\x02 \x01(\v2\x1b.mapreduce.SubmitJobRequestH\x00R\tsubmitJobB\x05\n" +
	"\x03msg\"8\n" +
	"\fBossToClient\x12!\n" +
	"\vstatus_dump\x18\x01 \x01(\tH\x00R\n" +
	"statusDumpB\x05\n" +
	"\x03msg\"G\n" +
	"\vClientHello\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"\xa9\x02\n" +
	"\x10SubmitJobRequest\x12\x19\n" +
	"\bcode_uri\x18\x01 \x01(\tR\acodeUri\x12\x1f\n" +
	"\vinput_files\x18\x02 \x03(\tR\n" +
	"inputFiles\x12#\n" +
	"\rreducer_count\x18\x03 \x01(\x05R\freducerCount\x12'\n" +
	"\x0fenable_combiner\x18\x04 \x01(\bR\x0eenableCombiner\x124\n" +
	"\n" +
	"input_type\x18\x05 \x01(\x0e2\x15.mapreduce.DataFormatR\tinputType\x126\n" +
	"\voutput_type\x18\x06 \x01(\x0e2\x15.mapreduce.DataFormatR\n" +
	"outputType\x12\x1d\n" +
	"\n" +
	"output_dir\x18\a \x01(\tR\toutputDir*-\n" +
	"\n" +
	"DataFormat\x12\b\n" +
	"\x04TEXT\x10\x00\x12\v\n" +
	"\aPARQUET\x10\x01\x12\b\n" +
	"\x04JSON\x10\x022V\n" +
	"\rClientService\x12E\n" +
	"\rClientControl\x12\x17.mapreduce.ClientToBoss\x1a\x17.mapreduce.BossToClient(\x010\x01B\x0eZ\fmapreduce/pbb\x06proto3"

var (
	file_proto_client_proto_rawDescOnce sync.Once
	file_proto_client_proto_rawDescData []byte
)

func file_proto_client_proto_rawDescGZIP() []byte {
	file_proto_client_proto_rawDescOnce.Do(func() {
		file_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)))
	})
	return file_proto_client_proto_rawDescData
}

var file_proto_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_client_proto_goTypes = []any{
	(DataFormat)(0),          // 0: mapreduce.DataFormat
	(*ClientToBoss)(nil),     // 1: mapreduce.ClientToBoss
	(*BossToClient)(nil),     // 2: mapreduce.BossToClient
	(*ClientHello)(nil),      // 3: mapreduce.ClientHello
	(*SubmitJobRequest)(nil), // 4: mapreduce.SubmitJobRequest
}
var file_proto_client_proto_depIdxs = []int32{
	3, // 0: mapreduce.ClientToBoss.hello:type_name -> mapreduce.ClientHello
	4, // 1: mapreduce.ClientToBoss.submit_job:type_name -> mapreduce.SubmitJobRequest
	0, // 2: mapreduce.SubmitJobRequest.input_type:type_name -> mapreduce.DataFormat
	0, // 3: mapreduce.SubmitJobRequest.output_type:type_name -> mapreduce.DataFormat
	1, // 4: mapreduce.ClientService.ClientControl:input_type -> mapreduce.ClientToBoss
	2, // 5: mapreduce.ClientService.ClientControl:output_type -> mapreduce.BossToClient
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_client_proto_init() }
func file_proto_client_proto_init() {
	if File_proto_client_proto != nil {
		return
	}
	file_proto_client_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientToBoss_Hello)(nil),
		(*ClientToBoss_SubmitJob)(nil),
	}
	file_proto_client_proto_msgTypes[1].OneofWrappers = []any{
		(*BossToClient_StatusDump)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_proto_goTypes,
		DependencyIndexes: file_proto_client_proto_depIdxs,
		EnumInfos:         file_proto_client_proto_enumTypes,
		MessageInfos:      file_proto_client_proto_msgTypes,
	}.Build()
	File_proto_client_proto = out.File
	file_proto_client_proto_goTypes = nil
	file_proto_client_proto_depIdxs = nil
}
