// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type TaskType int32

const (
	TaskType_MAP    TaskType = 0
	TaskType_REDUCE TaskType = 1
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "MAP",
		1: "REDUCE",
	}
	TaskType_value = map[string]int32{
		"MAP":    0,
		"REDUCE": 1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_worker_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_QUEUED      TaskStatus = 0
	TaskStatus_ASSIGNED    TaskStatus = 1
	TaskStatus_IN_PROGRESS TaskStatus = 2
	TaskStatus_COMPLETED   TaskStatus = 3
	TaskStatus_FAILED      TaskStatus = 4
	TaskStatus_CANCELED    TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "QUEUED",
		1: "ASSIGNED",
		2: "IN_PROGRESS",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELED",
	}
	TaskStatus_value = map[string]int32{
		"QUEUED":      0,
		"ASSIGNED":    1,
		"IN_PROGRESS": 2,
		"COMPLETED":   3,
		"FAILED":      4,
		"CANCELED":    5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_worker_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

type DataFormat int32

const (
	DataFormat_TEXT    DataFormat = 0
	DataFormat_PARQUET DataFormat = 1
	DataFormat_JSON    DataFormat = 2
)

// Enum value maps for DataFormat.
var (
	DataFormat_name = map[int32]string{
		0: "TEXT",
		1: "PARQUET",
		2: "JSON",
	}
	DataFormat_value = map[string]int32{
		"TEXT":    0,
		"PARQUET": 1,
		"JSON":    2,
	}
)

func (x DataFormat) Enum() *DataFormat {
	p := new(DataFormat)
	*p = x
	return p
}

func (x DataFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_proto_enumTypes[2].Descriptor()
}

func (DataFormat) Type() protoreflect.EnumType {
	return &file_proto_worker_proto_enumTypes[2]
}

func (x DataFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataFormat.Descriptor instead.
func (DataFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

// Messages from boss to worker
type BossToWorker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*BossToWorker_AssignTask
	//	*BossToWorker_Ping
	//	*BossToWorker_Kill
	Msg           isBossToWorker_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossToWorker) Reset() {
	*x = BossToWorker{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossToWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossToWorker) ProtoMessage() {}

func (x *BossToWorker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossToWorker.ProtoReflect.Descriptor instead.
func (*BossToWorker) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *BossToWorker) GetMsg() isBossToWorker_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *BossToWorker) GetAssignTask() *AssignTask {
	if x != nil {
		if x, ok := x.Msg.(*BossToWorker_AssignTask); ok {
			return x.AssignTask
		}
	}
	return nil
}

func (x *BossToWorker) GetPing() int32 {
	if x != nil {
		if x, ok := x.Msg.(*BossToWorker_Ping); ok {
			return x.Ping
		}
	}
	return 0
}

func (x *BossToWorker) GetKill() int32 {
	if x != nil {
		if x, ok := x.Msg.(*BossToWorker_Kill); ok {
			return x.Kill
		}
	}
	return 0
}

type isBossToWorker_Msg interface {
	isBossToWorker_Msg()
}

type BossToWorker_AssignTask struct {
	AssignTask *AssignTask `protobuf:"bytes,1,opt,name=assign_task,json=assignTask,proto3,oneof"`
}

type BossToWorker_Ping struct {
	Ping int32 `protobuf:"varint,2,opt,name=ping,proto3,oneof"` // Request pong to check if worker is alive
}

type BossToWorker_Kill struct {
	Kill int32 `protobuf:"varint,3,opt,name=kill,proto3,oneof"` // Kill message to the worker
}

func (*BossToWorker_AssignTask) isBossToWorker_Msg() {}

func (*BossToWorker_Ping) isBossToWorker_Msg() {}

func (*BossToWorker_Kill) isBossToWorker_Msg() {}

// Messages from worker to boss
type WorkerToBoss struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerToBoss_Hello
	//	*WorkerToBoss_Pong
	//	*WorkerToBoss_TaskResult
	//	*WorkerToBoss_Log
	//	*WorkerToBoss_TaskProgress
	Msg           isWorkerToBoss_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerToBoss) Reset() {
	*x = WorkerToBoss{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerToBoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerToBoss) ProtoMessage() {}

func (x *WorkerToBoss) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerToBoss.ProtoReflect.Descriptor instead.
func (*WorkerToBoss) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerToBoss) GetMsg() isWorkerToBoss_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerToBoss) GetHello() *WorkerHello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToBoss_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerToBoss) GetPong() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToBoss_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *WorkerToBoss) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToBoss_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerToBoss) GetLog() string {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToBoss_Log); ok {
			return x.Log
		}
	}
	return ""
}

func (x *WorkerToBoss) GetTaskProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToBoss_TaskProgress); ok {
			return x.TaskProgress
		}
	}
	return nil
}

type isWorkerToBoss_Msg interface {
	isWorkerToBoss_Msg()
}

type WorkerToBoss_Hello struct {
	Hello *WorkerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // Worker greeting, boss registers it
}

type WorkerToBoss_Pong struct {
	Pong *Heartbeat `protobuf:"bytes,2,opt,name=pong,proto3,oneof"` // Non-task related pong response
}

type WorkerToBoss_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"` // Task completion with output paths
}

type WorkerToBoss_Log struct {
	Log string `protobuf:"bytes,4,opt,name=log,proto3,oneof"` // Logging messages
}

type WorkerToBoss_TaskProgress struct {
	TaskProgress *TaskProgress `protobuf:"bytes,5,opt,name=task_progress,json=taskProgress,proto3,oneof"` // Progress updates to extend lease
}

func (*WorkerToBoss_Hello) isWorkerToBoss_Msg() {}

func (*WorkerToBoss_Pong) isWorkerToBoss_Msg() {}

func (*WorkerToBoss_TaskResult) isWorkerToBoss_Msg() {}

func (*WorkerToBoss_Log) isWorkerToBoss_Msg() {}

func (*WorkerToBoss_TaskProgress) isWorkerToBoss_Msg() {}

// Worker introduces itself when connecting
type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      *WorkerId              `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // Worker generates its own UUID
	Slots         int32                  `protobuf:"varint,2,opt,name=slots,proto3" json:"slots,omitempty"`                      // Number of concurrent tasks it can handle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerHello) GetWorkerId() *WorkerId {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *WorkerHello) GetSlots() int32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

// Heartbeat/pong message
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Could include CPU usage, memory stats, etc. in the future
	CpuUsage      float64 `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   int64   `protobuf:"varint,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Heartbeat) GetMemoryUsage() int64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// Task progress reporting to extend lease
type TaskProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *TaskId                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"` // 0-100
	ReadBytes     int64                  `protobuf:"varint,3,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes    int64                  `protobuf:"varint,4,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	RecordsIn     int64                  `protobuf:"varint,5,opt,name=records_in,json=recordsIn,proto3" json:"records_in,omitempty"`
	RecordsOut    int64                  `protobuf:"varint,6,opt,name=records_out,json=recordsOut,proto3" json:"records_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *TaskProgress) GetTaskId() *TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *TaskProgress) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *TaskProgress) GetReadBytes() int64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *TaskProgress) GetWriteBytes() int64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *TaskProgress) GetRecordsIn() int64 {
	if x != nil {
		return x.RecordsIn
	}
	return 0
}

func (x *TaskProgress) GetRecordsOut() int64 {
	if x != nil {
		return x.RecordsOut
	}
	return 0
}

// Task assignment from boss to worker
type AssignTask struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId *TaskId                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type   TaskType               `protobuf:"varint,2,opt,name=type,proto3,enum=mapreduce.TaskType" json:"type,omitempty"`
	JobId  string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// User code with MAP/REDUCE functions
	CodeUri string `protobuf:"bytes,4,opt,name=code_uri,json=codeUri,proto3" json:"code_uri,omitempty"`
	// Lease management
	LeaseId string `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseMs int64  `protobuf:"varint,6,opt,name=lease_ms,json=leaseMs,proto3" json:"lease_ms,omitempty"` // Lease duration in milliseconds
	Attempt int32  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`                // Retry attempt number
	// Output directory (worker determines specific filenames)
	OutputDir string `protobuf:"bytes,8,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	// Data formats
	InputType  DataFormat `protobuf:"varint,9,opt,name=input_type,json=inputType,proto3,enum=mapreduce.DataFormat" json:"input_type,omitempty"`
	OutputType DataFormat `protobuf:"varint,10,opt,name=output_type,json=outputType,proto3,enum=mapreduce.DataFormat" json:"output_type,omitempty"`
	// Map-specific fields (set when type = MAP)
	InputUri       string `protobuf:"bytes,20,opt,name=input_uri,json=inputUri,proto3" json:"input_uri,omitempty"`                    // Path to input file
	ByteStart      int64  `protobuf:"varint,21,opt,name=byte_start,json=byteStart,proto3" json:"byte_start,omitempty"`                // Start byte offset
	ByteEnd        int64  `protobuf:"varint,22,opt,name=byte_end,json=byteEnd,proto3" json:"byte_end,omitempty"`                      // End byte offset
	ReducerCount   int32  `protobuf:"varint,23,opt,name=reducer_count,json=reducerCount,proto3" json:"reducer_count,omitempty"`       // Number of partitions to create
	EnableCombiner bool   `protobuf:"varint,24,opt,name=enable_combiner,json=enableCombiner,proto3" json:"enable_combiner,omitempty"` // Whether to use combiner function
	// Reduce-specific fields (set when type = REDUCE)
	InputPaths    []string `protobuf:"bytes,30,rep,name=input_paths,json=inputPaths,proto3" json:"input_paths,omitempty"` // List of input files for this reducer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTask) Reset() {
	*x = AssignTask{}
	mi := &file_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTask) ProtoMessage() {}

func (x *AssignTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTask.ProtoReflect.Descriptor instead.
func (*AssignTask) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *AssignTask) GetTaskId() *TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *AssignTask) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_MAP
}

func (x *AssignTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssignTask) GetCodeUri() string {
	if x != nil {
		return x.CodeUri
	}
	return ""
}

func (x *AssignTask) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *AssignTask) GetLeaseMs() int64 {
	if x != nil {
		return x.LeaseMs
	}
	return 0
}

func (x *AssignTask) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *AssignTask) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *AssignTask) GetInputType() DataFormat {
	if x != nil {
		return x.InputType
	}
	return DataFormat_TEXT
}

func (x *AssignTask) GetOutputType() DataFormat {
	if x != nil {
		return x.OutputType
	}
	return DataFormat_TEXT
}

func (x *AssignTask) GetInputUri() string {
	if x != nil {
		return x.InputUri
	}
	return ""
}

func (x *AssignTask) GetByteStart() int64 {
	if x != nil {
		return x.ByteStart
	}
	return 0
}

func (x *AssignTask) GetByteEnd() int64 {
	if x != nil {
		return x.ByteEnd
	}
	return 0
}

func (x *AssignTask) GetReducerCount() int32 {
	if x != nil {
		return x.ReducerCount
	}
	return 0
}

func (x *AssignTask) GetEnableCombiner() bool {
	if x != nil {
		return x.EnableCombiner
	}
	return false
}

func (x *AssignTask) GetInputPaths() []string {
	if x != nil {
		return x.InputPaths
	}
	return nil
}

// Task completion result from worker to boss
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *TaskId                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          TaskType               `protobuf:"varint,2,opt,name=type,proto3,enum=mapreduce.TaskType" json:"type,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=mapreduce.TaskStatus" json:"status,omitempty"`    // OK, FAILED, CANCELED, LOST
	OutputPaths   []string               `protobuf:"bytes,10,rep,name=output_paths,json=outputPaths,proto3" json:"output_paths,omitempty"` // Files created by this task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetTaskId() *TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *TaskResult) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_MAP
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_QUEUED
}

func (x *TaskResult) GetOutputPaths() []string {
	if x != nil {
		return x.OutputPaths
	}
	return nil
}

// Shared data types
type JobId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobId) Reset() {
	*x = JobId{}
	mi := &file_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobId) ProtoMessage() {}

func (x *JobId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobId.ProtoReflect.Descriptor instead.
func (*JobId) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *JobId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskId) Reset() {
	*x = TaskId{}
	mi := &file_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskId) ProtoMessage() {}

func (x *TaskId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskId.ProtoReflect.Descriptor instead.
func (*TaskId) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{8}
}

func (x *TaskId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkerId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerId) Reset() {
	*x = WorkerId{}
	mi := &file_proto_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerId) ProtoMessage() {}

func (x *WorkerId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerId.ProtoReflect.Descriptor instead.
func (*WorkerId) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{9}
}

func (x *WorkerId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\tmapreduce\"{\n" +
	"\fBossToWorker\x128\n" +
	"\vassign_task\x18\x01 \x01(\v2\x15.mapreduce.AssignTaskH\x00R\n" +
	"assignTask\x12\x14\n" +
	"\x04ping\x18\x02 \x01(\x05H\x00R\x04ping\x12\x14\n" +
	"\x04kill\x18\x03 \x01(\x05H\x00R\x04killB\x05\n" +
	"\x03msg\"\xff\x01\n" +
	"\fWorkerToBoss\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.mapreduce.WorkerHelloH\x00R\x05hello\x12*\n" +
	"\x04pong\x18\x02 \x01(\v2\x14.mapreduce.HeartbeatH\x00R\x04pong\x128\n" +
	"\vtask_result\x18\x03 \x01(\v2\x15.mapreduce.TaskResultH\x00R\n" +
	"taskResult\x12\x12\n" +
	"\x03log\x18\x04 \x01(\tH\x00R\x03log\x12>\n" +
	"\rtask_progress\x18\x05 \x01(\v2\x17.mapreduce.TaskProgressH\x00R\ftaskProgressB\x05\n" +
	"\x03msg\"U\n" +
	"\vWorkerHello\x120\n" +
	"\tworker_id\x18\x01 \x01(\v2\x13.mapreduce.WorkerIdR\bworkerId\x12\x14\n" +
	"\x05slots\x18\x02 \x01(\x05R\x05slots\"K\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x03R\vmemoryUsage\"\xd4\x01\n" +
	"\fTaskProgress\x12*\n" +
	"\atask_id\x18\x01 \x01(\v2\x11.mapreduce.TaskIdR\x06taskId\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x03 \x01(\x03R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x04 \x01(\x03R\n" +
	"writeBytes\x12\x1d\n" +
	"\n" +
	"records_in\x18\x05 \x01(\x03R\trecordsIn\x12\x1f\n" +
	"\vrecords_out\x18\x06 \x01(\x03R\n" +
	"recordsOut\"\xb6\x04\n" +
	"\n" +
	"AssignTask\x12*\n" +
	"\atask_id\x18\x01 \x01(\v2\x11.mapreduce.TaskIdR\x06taskId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.mapreduce.TaskTypeR\x04type\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x19\n" +
	"\bcode_uri\x18\x04 \x01(\tR\acodeUri\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x12\x19\n" +
	"\blease_ms\x18\x06 \x01(\x03R\aleaseMs\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"output_dir\x18\b \x01(\tR\toutputDir\x124\n" +
	"\n" +
	"input_type\x18\t \x01(\x0e2\x15.mapreduce.DataFormatR\tinputType\x126\n" +
	"\voutput_type\x18\n" +
	" \x01(\x0e2\x15.mapreduce.DataFormatR\n" +
	"outputType\x12\x1b\n" +
	"\tinput_uri\x18\x14 \x01(\tR\binputUri\x12\x1d\n" +
	"\n" +
	"byte_start\x18\x15 \x01(\x03R\tbyteStart\x12\x19\n" +
	"\bbyte_end\x18\x16 \x01(\x03R\abyteEnd\x12#\n" +
	"\rreducer_count\x18\x17 \x01(\x05R\freducerCount\x12'\n" +
	"\x0fenable_combiner\x18\x18 \x01(\bR\x0eenableCombiner\x12\x1f\n" +
	"\vinput_paths\x18\x1e \x03(\tR\n" +
	"inputPaths\"\xb3\x01\n" +
	"\n" +
	"TaskResult\x12*\n" +
	"\atask_id\x18\x01 \x01(\v2\x11.mapreduce.TaskIdR\x06taskId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.mapreduce.TaskTypeR\x04type\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.mapreduce.TaskStatusR\x06status\x12!\n" +
	"\foutput_paths\x18\n" +
	" \x03(\tR\voutputPaths\"\x17\n" +
	"\x05JobId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x06TaskId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bWorkerId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*\x1f\n" +
	"\bTaskType\x12\a\n" +
	"\x03MAP\x10\x00\x12\n" +
	"\n" +
	"\x06REDUCE\x10\x01*`\n" +
	"\n" +
	"TaskStatus\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\f\n" +
	"\bASSIGNED\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x05*-\n" +
	"\n" +
	"DataFormat\x12\b\n" +
	"\x04TEXT\x10\x00\x12\v\n" +
	"\aPARQUET\x10\x01\x12\b\n" +
	"\x04JSON\x10\x022P\n" +
	"\rWorkerService\x12?\n" +
	"\aControl\x12\x17.mapreduce.WorkerToBoss\x1a\x17.mapreduce.BossToWorker(\x010\x01B\x0eZ\fmapreduce/pbb\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_worker_proto_goTypes = []any{
	(TaskType)(0),        // 0: mapreduce.TaskType
	(TaskStatus)(0),      // 1: mapreduce.TaskStatus
	(DataFormat)(0),      // 2: mapreduce.DataFormat
	(*BossToWorker)(nil), // 3: mapreduce.BossToWorker
	(*WorkerToBoss)(nil), // 4: mapreduce.WorkerToBoss
	(*WorkerHello)(nil),  // 5: mapreduce.WorkerHello
	(*Heartbeat)(nil),    // 6: mapreduce.Heartbeat
	(*TaskProgress)(nil), // 7: mapreduce.TaskProgress
	(*AssignTask)(nil),   // 8: mapreduce.AssignTask
	(*TaskResult)(nil),   // 9: mapreduce.TaskResult
	(*JobId)(nil),        // 10: mapreduce.JobId
	(*TaskId)(nil),       // 11: mapreduce.TaskId
	(*WorkerId)(nil),     // 12: mapreduce.WorkerId
}
var file_proto_worker_proto_depIdxs = []int32{
	8,  // 0: mapreduce.BossToWorker.assign_task:type_name -> mapreduce.AssignTask
	5,  // 1: mapreduce.WorkerToBoss.hello:type_name -> mapreduce.WorkerHello
	6,  // 2: mapreduce.WorkerToBoss.pong:type_name -> mapreduce.Heartbeat
	9,  // 3: mapreduce.WorkerToBoss.task_result:type_name -> mapreduce.TaskResult
	7,  // 4: mapreduce.WorkerToBoss.task_progress:type_name -> mapreduce.TaskProgress
	12, // 5: mapreduce.WorkerHello.worker_id:type_name -> mapreduce.WorkerId
	11, // 6: mapreduce.TaskProgress.task_id:type_name -> mapreduce.TaskId
	11, // 7: mapreduce.AssignTask.task_id:type_name -> mapreduce.TaskId
	0,  // 8: mapreduce.AssignTask.type:type_name -> mapreduce.TaskType
	2,  // 9: mapreduce.AssignTask.input_type:type_name -> mapreduce.DataFormat
	2,  // 10: mapreduce.AssignTask.output_type:type_name -> mapreduce.DataFormat
	11, // 11: mapreduce.TaskResult.task_id:type_name -> mapreduce.TaskId
	0,  // 12: mapreduce.TaskResult.type:type_name -> mapreduce.TaskType
	1,  // 13: mapreduce.TaskResult.status:type_name -> mapreduce.TaskStatus
	4,  // 14: mapreduce.WorkerService.Control:input_type -> mapreduce.WorkerToBoss
	3,  // 15: mapreduce.WorkerService.Control:output_type -> mapreduce.BossToWorker
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	file_proto_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*BossToWorker_AssignTask)(nil),
		(*BossToWorker_Ping)(nil),
		(*BossToWorker_Kill)(nil),
	}
	file_proto_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*WorkerToBoss_Hello)(nil),
		(*WorkerToBoss_Pong)(nil),
		(*WorkerToBoss_TaskResult)(nil),
		(*WorkerToBoss_Log)(nil),
		(*WorkerToBoss_TaskProgress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		EnumInfos:         file_proto_worker_proto_enumTypes,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
